namespace: community
name: proxysql
version: 1.2.0-dev
readme: README.md
authors:
  - Ansible ProxySQL community
  - Akim Lindberg (@akimrx)
  - Ben Mildren (@bmildren)
description: ProxySQL collection for Ansible
license_file: LICENSE
tags:
  - database
  - mysql
  - proxysql
repository: https://github.com/ansible-collections/community.proxysql
documentation: https://docs.ansible.com/ansible/latest/collections/community/proxysql/index.html
homepage: https://github.com/ansible-collections/community.proxysql
issues: https://github.com/ansible-collections/community.proxysql/issues
