namespace: community
name: proxysql
version: 1.0.1
readme: README.md
authors:
  - Ben Mildren (@bmildren)
  - Akim Lindberg (@akimrx)
description: ProxySQL collection for Ansible
license_file: LICENSE
tags:
  - database
  - mysql
  - proxysql
repository: https://github.com/ansible-collections/community.proxysql
documentation: https://github.com/ansible-collections/community.proxysql
homepage: https://github.com/ansible-collections/community.proxysql
issues: https://github.com/ansible-collections/community.proxysql/issues
